let g:floaterm_title="hieu tran's system environment"
let g:floaterm_width=0.95
let g:floaterm_height=0.5
let g:floaterm_position="bottom"
let g:floaterm_wintype="float"
let g:floaterm_borderchars=""
let g:floaterm_rootmarkers=['.project', '.git', '.hg', '.svn', '.root']
let g:floaterm_autoclose=1
let g:floaterm_autoinsert="v:true"
let g:floaterm_keymap_new    = '<F7>'
let g:floaterm_keymap_prev   = '<F8>'
let g:floaterm_keymap_next   = '<F9>'
let g:floaterm_keymap_toggle = '<F12>'
